create-temporary-directory: don't try to mkdir if a file with the same name exists
By checking for the existence of a _directory_ in
create-temporary-directory, the following program would eventually
cause a runtime error, as a _file_ with the same name would exist:

  (use files)

  (let loop ()
    (create-temporary-file "")
    (create-temporary-directory)
    (loop))

  Error: (create-temporary-directory) cannot create temporary directory
  - File exists: ...

Use file-exists? instead of directory-exists? to work around this
issue.

Signed-off-by: Evan Hanson <evhan@foldling.org>